import Hero from "@components/Hero";
import Head from "next/head";
import { DrawChallenge } from "components";

export default function Home() {
    return (
        <div className="overflow-hidden flex flex-col items-center">
            <Head>
                <title> Gladys P.Nut </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero heading={"Gladys P. Nut"} message={`Artist and Designer based in the Netherlands, lover of everything cute. \n Specializing in character design and everything kawaii!`} />
            <DrawChallenge className="rounded mx-auto" />
        </div>
    );
}
