import { Header } from "components";
import Head from "next/head";

export default function Home() {
    return (
        <div className="container mx-auto">
            <Head>
                <title> Gladys P.Nut </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="min-h-[65vh] flex flex-col flex-1 justify-center items-center text-secondary">
                <h1 className="text-7xl"> Welcome </h1>
                <div className="container--grid">
                    Test
                </div>
            </main>
        </div>
    );
}
